language: node_js
node_js:
  - lts/*
install:
  - yarn install
script:
  - node getReadme.js && node append.js && yarn build && node deleteComponent.js
deploy:
  provider: pages
  cleanup: true
  local_dir: .vuepress/dist
  repo: yancqS/blog
  github_token: $GH_TOKEN
  keep_history: true
  on:
    branch: master