language: node_js
node_js:
  - lts/*
install:
  - yarn install
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: .vuepress/dist
  repo: yancqS/blog
  github_token: $GH_TOKEN
  keep_history: true
  on:
    branch: master